//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bussiness.CRM.CRM_LoginService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRM.CRM_LoginService.CRM_LoginSoap")]
    public interface CRM_LoginSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bussiness.CRM.CRM_LoginService.CRM_LoginInfo Login(string name, string password, string OPENID, string WXDLCS, int PC, int WX);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WX_SYS_Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int WX_SYS_Update(Bussiness.CRM.CRM_LoginService.CRM_WX_SYS model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WX_SYS_ReadByWXAPPID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bussiness.CRM.CRM_LoginService.CRM_WX_SYS WX_SYS_ReadByWXAPPID(string WXAPPID, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ValidateToken(string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login_SSO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bussiness.CRM.CRM_LoginService.TokenInfo Login_SSO(string name, string password, string OPENID, string WXDLCS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login_SSO_TOKEN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bussiness.CRM.CRM_LoginService.CRM_LoginInfo Login_SSO_TOKEN(string TOKENID, int PC, int WX);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CRM_LoginInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TokenInfo tokenInfoField;
        
        private CRM_JURISDICTION_GROUP[] jURISDICTION_GROUPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TokenInfo TokenInfo {
            get {
                return this.tokenInfoField;
            }
            set {
                this.tokenInfoField = value;
                this.RaisePropertyChanged("TokenInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public CRM_JURISDICTION_GROUP[] JURISDICTION_GROUP {
            get {
                return this.jURISDICTION_GROUPField;
            }
            set {
                this.jURISDICTION_GROUPField = value;
                this.RaisePropertyChanged("JURISDICTION_GROUP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TokenInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string access_tokenField;
        
        private string expires_inField;
        
        private string mSGField;
        
        private string mESSAGEField;
        
        private int sTAFFIDField;
        
        private string tOKENIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string access_token {
            get {
                return this.access_tokenField;
            }
            set {
                this.access_tokenField = value;
                this.RaisePropertyChanged("access_token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string expires_in {
            get {
                return this.expires_inField;
            }
            set {
                this.expires_inField = value;
                this.RaisePropertyChanged("expires_in");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MSG {
            get {
                return this.mSGField;
            }
            set {
                this.mSGField = value;
                this.RaisePropertyChanged("MSG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int STAFFID {
            get {
                return this.sTAFFIDField;
            }
            set {
                this.sTAFFIDField = value;
                this.RaisePropertyChanged("STAFFID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TOKENID {
            get {
                return this.tOKENIDField;
            }
            set {
                this.tOKENIDField = value;
                this.RaisePropertyChanged("TOKENID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CRM_WX_SYS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int wX_SYSIDField;
        
        private string wXAPPIDField;
        
        private string aCCESS_TOKENField;
        
        private string tICKETField;
        
        private string jLTIMEField;
        
        private int eXPIRES_INField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int WX_SYSID {
            get {
                return this.wX_SYSIDField;
            }
            set {
                this.wX_SYSIDField = value;
                this.RaisePropertyChanged("WX_SYSID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string WXAPPID {
            get {
                return this.wXAPPIDField;
            }
            set {
                this.wXAPPIDField = value;
                this.RaisePropertyChanged("WXAPPID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ACCESS_TOKEN {
            get {
                return this.aCCESS_TOKENField;
            }
            set {
                this.aCCESS_TOKENField = value;
                this.RaisePropertyChanged("ACCESS_TOKEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TICKET {
            get {
                return this.tICKETField;
            }
            set {
                this.tICKETField = value;
                this.RaisePropertyChanged("TICKET");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string JLTIME {
            get {
                return this.jLTIMEField;
            }
            set {
                this.jLTIMEField = value;
                this.RaisePropertyChanged("JLTIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int EXPIRES_IN {
            get {
                return this.eXPIRES_INField;
            }
            set {
                this.eXPIRES_INField = value;
                this.RaisePropertyChanged("EXPIRES_IN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CRM_HG_RIGHT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int wxField;
        
        private int pcField;
        
        private int rIGHTIDField;
        
        private int rGROUPIDField;
        
        private string rIGHTNAMEField;
        
        private int rIGHTNOField;
        
        private string rIGHTADDField;
        
        private string rIGHTMEMOField;
        
        private int iSACTIVEField;
        
        private string iMAGELJField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int WX {
            get {
                return this.wxField;
            }
            set {
                this.wxField = value;
                this.RaisePropertyChanged("WX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int PC {
            get {
                return this.pcField;
            }
            set {
                this.pcField = value;
                this.RaisePropertyChanged("PC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int RIGHTID {
            get {
                return this.rIGHTIDField;
            }
            set {
                this.rIGHTIDField = value;
                this.RaisePropertyChanged("RIGHTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int RGROUPID {
            get {
                return this.rGROUPIDField;
            }
            set {
                this.rGROUPIDField = value;
                this.RaisePropertyChanged("RGROUPID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RIGHTNAME {
            get {
                return this.rIGHTNAMEField;
            }
            set {
                this.rIGHTNAMEField = value;
                this.RaisePropertyChanged("RIGHTNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int RIGHTNO {
            get {
                return this.rIGHTNOField;
            }
            set {
                this.rIGHTNOField = value;
                this.RaisePropertyChanged("RIGHTNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string RIGHTADD {
            get {
                return this.rIGHTADDField;
            }
            set {
                this.rIGHTADDField = value;
                this.RaisePropertyChanged("RIGHTADD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string RIGHTMEMO {
            get {
                return this.rIGHTMEMOField;
            }
            set {
                this.rIGHTMEMOField = value;
                this.RaisePropertyChanged("RIGHTMEMO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int ISACTIVE {
            get {
                return this.iSACTIVEField;
            }
            set {
                this.iSACTIVEField = value;
                this.RaisePropertyChanged("ISACTIVE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string IMAGELJ {
            get {
                return this.iMAGELJField;
            }
            set {
                this.iMAGELJField = value;
                this.RaisePropertyChanged("IMAGELJ");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CRM_HG_RIGHTGROUP : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int rGROUPIDField;
        
        private string rGROUPNAMEField;
        
        private int pRGROUPIDField;
        
        private int pRIGHTNOField;
        
        private string rGROUPMEMOField;
        
        private int iSACTIVEField;
        
        private string iMAGELJField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int RGROUPID {
            get {
                return this.rGROUPIDField;
            }
            set {
                this.rGROUPIDField = value;
                this.RaisePropertyChanged("RGROUPID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RGROUPNAME {
            get {
                return this.rGROUPNAMEField;
            }
            set {
                this.rGROUPNAMEField = value;
                this.RaisePropertyChanged("RGROUPNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int PRGROUPID {
            get {
                return this.pRGROUPIDField;
            }
            set {
                this.pRGROUPIDField = value;
                this.RaisePropertyChanged("PRGROUPID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int PRIGHTNO {
            get {
                return this.pRIGHTNOField;
            }
            set {
                this.pRIGHTNOField = value;
                this.RaisePropertyChanged("PRIGHTNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RGROUPMEMO {
            get {
                return this.rGROUPMEMOField;
            }
            set {
                this.rGROUPMEMOField = value;
                this.RaisePropertyChanged("RGROUPMEMO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ISACTIVE {
            get {
                return this.iSACTIVEField;
            }
            set {
                this.iSACTIVEField = value;
                this.RaisePropertyChanged("ISACTIVE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string IMAGELJ {
            get {
                return this.iMAGELJField;
            }
            set {
                this.iMAGELJField = value;
                this.RaisePropertyChanged("IMAGELJ");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CRM_JURISDICTION_GROUP : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CRM_HG_RIGHTGROUP cRM_HG_RIGHTGROUPField;
        
        private CRM_HG_RIGHT[] cRM_HG_RIGHTListField;
        
        private int sTAFFIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CRM_HG_RIGHTGROUP CRM_HG_RIGHTGROUP {
            get {
                return this.cRM_HG_RIGHTGROUPField;
            }
            set {
                this.cRM_HG_RIGHTGROUPField = value;
                this.RaisePropertyChanged("CRM_HG_RIGHTGROUP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public CRM_HG_RIGHT[] CRM_HG_RIGHTList {
            get {
                return this.cRM_HG_RIGHTListField;
            }
            set {
                this.cRM_HG_RIGHTListField = value;
                this.RaisePropertyChanged("CRM_HG_RIGHTList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int STAFFID {
            get {
                return this.sTAFFIDField;
            }
            set {
                this.sTAFFIDField = value;
                this.RaisePropertyChanged("STAFFID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CRM_LoginSoapChannel : Bussiness.CRM.CRM_LoginService.CRM_LoginSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRM_LoginSoapClient : System.ServiceModel.ClientBase<Bussiness.CRM.CRM_LoginService.CRM_LoginSoap>, Bussiness.CRM.CRM_LoginService.CRM_LoginSoap {
        
        public CRM_LoginSoapClient() {
        }
        
        public CRM_LoginSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRM_LoginSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRM_LoginSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRM_LoginSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public Bussiness.CRM.CRM_LoginService.CRM_LoginInfo Login(string name, string password, string OPENID, string WXDLCS, int PC, int WX) {
            return base.Channel.Login(name, password, OPENID, WXDLCS, PC, WX);
        }
        
        public int WX_SYS_Update(Bussiness.CRM.CRM_LoginService.CRM_WX_SYS model, string ptoken) {
            return base.Channel.WX_SYS_Update(model, ptoken);
        }
        
        public Bussiness.CRM.CRM_LoginService.CRM_WX_SYS WX_SYS_ReadByWXAPPID(string WXAPPID, string ptoken) {
            return base.Channel.WX_SYS_ReadByWXAPPID(WXAPPID, ptoken);
        }
        
        public bool ValidateToken(string ptoken) {
            return base.Channel.ValidateToken(ptoken);
        }
        
        public Bussiness.CRM.CRM_LoginService.TokenInfo Login_SSO(string name, string password, string OPENID, string WXDLCS) {
            return base.Channel.Login_SSO(name, password, OPENID, WXDLCS);
        }
        
        public Bussiness.CRM.CRM_LoginService.CRM_LoginInfo Login_SSO_TOKEN(string TOKENID, int PC, int WX) {
            return base.Channel.Login_SSO_TOKEN(TOKENID, PC, WX);
        }
    }
}
