//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bussiness.RuK.DuiBiReportService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RuK.DuiBiReportService.DuiBiReportSoap")]
    public interface DuiBiReportSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RuK_DuiBiReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable RuK_DuiBiReport(Bussiness.RuK.DuiBiReportService.RuK_DuiBiReport model, string ptoken);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RuK_DuiBiReport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mtNameField;
        
        private string typeNameField;
        
        private string mtUnitField;
        
        private double lastmtNumber2Field;
        
        private double lastmtTotal2Field;
        
        private double lastprice2Field;
        
        private double mtNumber1Field;
        
        private double mtTotal1Field;
        
        private double price1Field;
        
        private double mtNumber2Field;
        
        private double mtTotal2Field;
        
        private double price2Field;
        
        private string yEARField;
        
        private string mONTHField;
        
        private int lbField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MtName {
            get {
                return this.mtNameField;
            }
            set {
                this.mtNameField = value;
                this.RaisePropertyChanged("MtName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TypeName {
            get {
                return this.typeNameField;
            }
            set {
                this.typeNameField = value;
                this.RaisePropertyChanged("TypeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MtUnit {
            get {
                return this.mtUnitField;
            }
            set {
                this.mtUnitField = value;
                this.RaisePropertyChanged("MtUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double LastmtNumber2 {
            get {
                return this.lastmtNumber2Field;
            }
            set {
                this.lastmtNumber2Field = value;
                this.RaisePropertyChanged("LastmtNumber2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double LastmtTotal2 {
            get {
                return this.lastmtTotal2Field;
            }
            set {
                this.lastmtTotal2Field = value;
                this.RaisePropertyChanged("LastmtTotal2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double Lastprice2 {
            get {
                return this.lastprice2Field;
            }
            set {
                this.lastprice2Field = value;
                this.RaisePropertyChanged("Lastprice2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double MtNumber1 {
            get {
                return this.mtNumber1Field;
            }
            set {
                this.mtNumber1Field = value;
                this.RaisePropertyChanged("MtNumber1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double MtTotal1 {
            get {
                return this.mtTotal1Field;
            }
            set {
                this.mtTotal1Field = value;
                this.RaisePropertyChanged("MtTotal1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double Price1 {
            get {
                return this.price1Field;
            }
            set {
                this.price1Field = value;
                this.RaisePropertyChanged("Price1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public double MtNumber2 {
            get {
                return this.mtNumber2Field;
            }
            set {
                this.mtNumber2Field = value;
                this.RaisePropertyChanged("MtNumber2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public double MtTotal2 {
            get {
                return this.mtTotal2Field;
            }
            set {
                this.mtTotal2Field = value;
                this.RaisePropertyChanged("MtTotal2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public double Price2 {
            get {
                return this.price2Field;
            }
            set {
                this.price2Field = value;
                this.RaisePropertyChanged("Price2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string YEAR {
            get {
                return this.yEARField;
            }
            set {
                this.yEARField = value;
                this.RaisePropertyChanged("YEAR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string MONTH {
            get {
                return this.mONTHField;
            }
            set {
                this.mONTHField = value;
                this.RaisePropertyChanged("MONTH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int LB {
            get {
                return this.lbField;
            }
            set {
                this.lbField = value;
                this.RaisePropertyChanged("LB");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DuiBiReportSoapChannel : Bussiness.RuK.DuiBiReportService.DuiBiReportSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DuiBiReportSoapClient : System.ServiceModel.ClientBase<Bussiness.RuK.DuiBiReportService.DuiBiReportSoap>, Bussiness.RuK.DuiBiReportService.DuiBiReportSoap {
        
        public DuiBiReportSoapClient() {
        }
        
        public DuiBiReportSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DuiBiReportSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DuiBiReportSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DuiBiReportSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Data.DataTable RuK_DuiBiReport(Bussiness.RuK.DuiBiReportService.RuK_DuiBiReport model, string ptoken) {
            return base.Channel.RuK_DuiBiReport(model, ptoken);
        }
    }
}
