//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bussiness.SSO.TOKEN_TOKENIDINFOService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SSO.TOKEN_TOKENIDINFOService.WS_SSO_TOKEN_TOKENIDINFOSoap")]
    public interface WS_SSO_TOKEN_TOKENIDINFOSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bussiness.SSO.TOKEN_TOKENIDINFOService.MES_RETURN SELECT(string TOKENID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UPDATE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bussiness.SSO.TOKEN_TOKENIDINFOService.MES_RETURN UPDATE(string TOKENID, int LB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/USERNAMEDY_INSERT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bussiness.SSO.TOKEN_TOKENIDINFOService.MES_RETURN USERNAMEDY_INSERT(Bussiness.SSO.TOKEN_TOKENIDINFOService.SSO_TOKEN_USERNAMEDY model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/USERNAMEDY_UPDATE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bussiness.SSO.TOKEN_TOKENIDINFOService.MES_RETURN USERNAMEDY_UPDATE(Bussiness.SSO.TOKEN_TOKENIDINFOService.SSO_TOKEN_USERNAMEDY model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/USERNAMEDY_SELECT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bussiness.SSO.TOKEN_TOKENIDINFOService.SSO_TOKEN_USERNAMEDY_SELECT USERNAMEDY_SELECT(Bussiness.SSO.TOKEN_TOKENIDINFOService.SSO_TOKEN_USERNAMEDY model, string ptoken);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MES_RETURN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string mESSAGEField;
        
        private int tIDField;
        
        private string gcField;
        
        private string tmField;
        
        private string bhField;
        
        private int xhField;
        
        private int tMSXField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int TID {
            get {
                return this.tIDField;
            }
            set {
                this.tIDField = value;
                this.RaisePropertyChanged("TID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string GC {
            get {
                return this.gcField;
            }
            set {
                this.gcField = value;
                this.RaisePropertyChanged("GC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TM {
            get {
                return this.tmField;
            }
            set {
                this.tmField = value;
                this.RaisePropertyChanged("TM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BH {
            get {
                return this.bhField;
            }
            set {
                this.bhField = value;
                this.RaisePropertyChanged("BH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int XH {
            get {
                return this.xhField;
            }
            set {
                this.xhField = value;
                this.RaisePropertyChanged("XH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int TMSX {
            get {
                return this.tMSXField;
            }
            set {
                this.tMSXField = value;
                this.RaisePropertyChanged("TMSX");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SSO_TOKEN_USERNAMEDY_SELECT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MES_RETURN mES_RETURNField;
        
        private SSO_TOKEN_USERNAMEDY[] sSO_TOKEN_USERNAMEDYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MES_RETURN MES_RETURN {
            get {
                return this.mES_RETURNField;
            }
            set {
                this.mES_RETURNField = value;
                this.RaisePropertyChanged("MES_RETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public SSO_TOKEN_USERNAMEDY[] SSO_TOKEN_USERNAMEDY {
            get {
                return this.sSO_TOKEN_USERNAMEDYField;
            }
            set {
                this.sSO_TOKEN_USERNAMEDYField = value;
                this.RaisePropertyChanged("SSO_TOKEN_USERNAMEDY");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SSO_TOKEN_USERNAMEDY : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int zHIDField;
        
        private int sTAFFIDField;
        
        private int zHLBField;
        
        private string zHUSERNAMEField;
        
        private int uPDATELBField;
        
        private int zHUSERIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ZHID {
            get {
                return this.zHIDField;
            }
            set {
                this.zHIDField = value;
                this.RaisePropertyChanged("ZHID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int STAFFID {
            get {
                return this.sTAFFIDField;
            }
            set {
                this.sTAFFIDField = value;
                this.RaisePropertyChanged("STAFFID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ZHLB {
            get {
                return this.zHLBField;
            }
            set {
                this.zHLBField = value;
                this.RaisePropertyChanged("ZHLB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ZHUSERNAME {
            get {
                return this.zHUSERNAMEField;
            }
            set {
                this.zHUSERNAMEField = value;
                this.RaisePropertyChanged("ZHUSERNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int UPDATELB {
            get {
                return this.uPDATELBField;
            }
            set {
                this.uPDATELBField = value;
                this.RaisePropertyChanged("UPDATELB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ZHUSERID {
            get {
                return this.zHUSERIDField;
            }
            set {
                this.zHUSERIDField = value;
                this.RaisePropertyChanged("ZHUSERID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_SSO_TOKEN_TOKENIDINFOSoapChannel : Bussiness.SSO.TOKEN_TOKENIDINFOService.WS_SSO_TOKEN_TOKENIDINFOSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_SSO_TOKEN_TOKENIDINFOSoapClient : System.ServiceModel.ClientBase<Bussiness.SSO.TOKEN_TOKENIDINFOService.WS_SSO_TOKEN_TOKENIDINFOSoap>, Bussiness.SSO.TOKEN_TOKENIDINFOService.WS_SSO_TOKEN_TOKENIDINFOSoap {
        
        public WS_SSO_TOKEN_TOKENIDINFOSoapClient() {
        }
        
        public WS_SSO_TOKEN_TOKENIDINFOSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_SSO_TOKEN_TOKENIDINFOSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_SSO_TOKEN_TOKENIDINFOSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_SSO_TOKEN_TOKENIDINFOSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Bussiness.SSO.TOKEN_TOKENIDINFOService.MES_RETURN SELECT(string TOKENID) {
            return base.Channel.SELECT(TOKENID);
        }
        
        public Bussiness.SSO.TOKEN_TOKENIDINFOService.MES_RETURN UPDATE(string TOKENID, int LB) {
            return base.Channel.UPDATE(TOKENID, LB);
        }
        
        public Bussiness.SSO.TOKEN_TOKENIDINFOService.MES_RETURN USERNAMEDY_INSERT(Bussiness.SSO.TOKEN_TOKENIDINFOService.SSO_TOKEN_USERNAMEDY model, string ptoken) {
            return base.Channel.USERNAMEDY_INSERT(model, ptoken);
        }
        
        public Bussiness.SSO.TOKEN_TOKENIDINFOService.MES_RETURN USERNAMEDY_UPDATE(Bussiness.SSO.TOKEN_TOKENIDINFOService.SSO_TOKEN_USERNAMEDY model, string ptoken) {
            return base.Channel.USERNAMEDY_UPDATE(model, ptoken);
        }
        
        public Bussiness.SSO.TOKEN_TOKENIDINFOService.SSO_TOKEN_USERNAMEDY_SELECT USERNAMEDY_SELECT(Bussiness.SSO.TOKEN_TOKENIDINFOService.SSO_TOKEN_USERNAMEDY model, string ptoken) {
            return base.Channel.USERNAMEDY_SELECT(model, ptoken);
        }
    }
}
