//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bussiness.CRM.HG_STAFFService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRM.HG_STAFFService.HG_STAFFSoap")]
    public interface HG_STAFFSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Create(Bussiness.CRM.HG_STAFFService.CRM_HG_STAFF model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Update(Bussiness.CRM.HG_STAFFService.CRM_HG_STAFF model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Delete(int STAFFID, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Report", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bussiness.CRM.HG_STAFFService.CRM_HG_STAFFList[] Report(Bussiness.CRM.HG_STAFFService.CRM_Report_STAFFModel model, string TYPE, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadBySTAFFID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bussiness.CRM.HG_STAFFService.CRM_HG_STAFF ReadBySTAFFID(int STAFFID, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadBySTAFFNO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bussiness.CRM.HG_STAFFService.CRM_HG_STAFF ReadBySTAFFNO(string STAFFNO, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadByROLEID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bussiness.CRM.HG_STAFFService.CRM_HG_STAFF ReadByROLEID(int ROLEID, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadByDUTYID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bussiness.CRM.HG_STAFFService.CRM_HG_STAFF[] ReadByDUTYID(int DUTYID, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadByParam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bussiness.CRM.HG_STAFFService.CRM_HG_STAFFList[] ReadByParam(Bussiness.CRM.HG_STAFFService.CRM_HG_STAFF model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bussiness.CRM.HG_STAFFService.CRM_HG_STAFFList[] ReadUser(string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadSTAFFBYKHIDANDDUTY", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bussiness.CRM.HG_STAFFService.STAFFDUTY_KH[] ReadSTAFFBYKHIDANDDUTY(int KHID, int DUTYID, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadSTAFF_KHGOURPBYSTAFFID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bussiness.CRM.HG_STAFFService.CRM_HG_STAFF[] ReadSTAFF_KHGOURPBYSTAFFID(int STAFFID, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadSTAFF_KHGroupByStaffidAndDuty", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bussiness.CRM.HG_STAFFService.CRM_HG_STAFF[] ReadSTAFF_KHGroupByStaffidAndDuty(int STAFFID, int DUTYID, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadStaff_BYDEPID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bussiness.CRM.HG_STAFFService.CRM_HG_STAFF[] ReadStaff_BYDEPID(int STAFFID, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadUser_STAFF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bussiness.CRM.HG_STAFFService.CRM_HG_STAFFList[] ReadUser_STAFF(Bussiness.CRM.HG_STAFFService.CRM_Report_STAFFModel model, string ptoken);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CRM_HG_STAFF : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int sTAFFIDField;
        
        private int dEPIDField;
        
        private string sTAFFNAMEField;
        
        private string sTAFFNOField;
        
        private string sTAFFUSERField;
        
        private string sTAFFPWField;
        
        private int sTAFFLXField;
        
        private string sTAFFRZSJField;
        
        private string sTAFFMPSJField;
        
        private int sTAFFSEXField;
        
        private string sTAFFJGField;
        
        private string sTAFFSFZHField;
        
        private string sTAFFSRField;
        
        private int sTAFFZZMMField;
        
        private int sTAFFXLField;
        
        private string sTAFFBYYXField;
        
        private int sTAFFHYZKField;
        
        private string sTAFFCZDZField;
        
        private int sTAFFZWJBField;
        
        private int sTAFFGWField;
        
        private string sTAFFWORKField;
        
        private string sTAFFMOBILEField;
        
        private string sTAFFTELField;
        
        private string sTAFFEMAILField;
        
        private int gjField;
        
        private int sTAFFSFField;
        
        private int sTAFFCITYField;
        
        private int bBIDField;
        
        private string sTAFFMEMOField;
        
        private string jLRQField;
        
        private int iSACTIVEField;
        
        private int bZIDField;
        
        private bool sISLOCKField;
        
        private bool sCANCELField;
        
        private bool iSSUPERField;
        
        private string xhField;
        
        private int e_COUNTField;
        
        private int sTAFFKHLXIDField;
        
        private int uSERLXField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int STAFFID {
            get {
                return this.sTAFFIDField;
            }
            set {
                this.sTAFFIDField = value;
                this.RaisePropertyChanged("STAFFID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int DEPID {
            get {
                return this.dEPIDField;
            }
            set {
                this.dEPIDField = value;
                this.RaisePropertyChanged("DEPID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string STAFFNAME {
            get {
                return this.sTAFFNAMEField;
            }
            set {
                this.sTAFFNAMEField = value;
                this.RaisePropertyChanged("STAFFNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string STAFFNO {
            get {
                return this.sTAFFNOField;
            }
            set {
                this.sTAFFNOField = value;
                this.RaisePropertyChanged("STAFFNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string STAFFUSER {
            get {
                return this.sTAFFUSERField;
            }
            set {
                this.sTAFFUSERField = value;
                this.RaisePropertyChanged("STAFFUSER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string STAFFPW {
            get {
                return this.sTAFFPWField;
            }
            set {
                this.sTAFFPWField = value;
                this.RaisePropertyChanged("STAFFPW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int STAFFLX {
            get {
                return this.sTAFFLXField;
            }
            set {
                this.sTAFFLXField = value;
                this.RaisePropertyChanged("STAFFLX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string STAFFRZSJ {
            get {
                return this.sTAFFRZSJField;
            }
            set {
                this.sTAFFRZSJField = value;
                this.RaisePropertyChanged("STAFFRZSJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string STAFFMPSJ {
            get {
                return this.sTAFFMPSJField;
            }
            set {
                this.sTAFFMPSJField = value;
                this.RaisePropertyChanged("STAFFMPSJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int STAFFSEX {
            get {
                return this.sTAFFSEXField;
            }
            set {
                this.sTAFFSEXField = value;
                this.RaisePropertyChanged("STAFFSEX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string STAFFJG {
            get {
                return this.sTAFFJGField;
            }
            set {
                this.sTAFFJGField = value;
                this.RaisePropertyChanged("STAFFJG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string STAFFSFZH {
            get {
                return this.sTAFFSFZHField;
            }
            set {
                this.sTAFFSFZHField = value;
                this.RaisePropertyChanged("STAFFSFZH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string STAFFSR {
            get {
                return this.sTAFFSRField;
            }
            set {
                this.sTAFFSRField = value;
                this.RaisePropertyChanged("STAFFSR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int STAFFZZMM {
            get {
                return this.sTAFFZZMMField;
            }
            set {
                this.sTAFFZZMMField = value;
                this.RaisePropertyChanged("STAFFZZMM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int STAFFXL {
            get {
                return this.sTAFFXLField;
            }
            set {
                this.sTAFFXLField = value;
                this.RaisePropertyChanged("STAFFXL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string STAFFBYYX {
            get {
                return this.sTAFFBYYXField;
            }
            set {
                this.sTAFFBYYXField = value;
                this.RaisePropertyChanged("STAFFBYYX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int STAFFHYZK {
            get {
                return this.sTAFFHYZKField;
            }
            set {
                this.sTAFFHYZKField = value;
                this.RaisePropertyChanged("STAFFHYZK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string STAFFCZDZ {
            get {
                return this.sTAFFCZDZField;
            }
            set {
                this.sTAFFCZDZField = value;
                this.RaisePropertyChanged("STAFFCZDZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int STAFFZWJB {
            get {
                return this.sTAFFZWJBField;
            }
            set {
                this.sTAFFZWJBField = value;
                this.RaisePropertyChanged("STAFFZWJB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int STAFFGW {
            get {
                return this.sTAFFGWField;
            }
            set {
                this.sTAFFGWField = value;
                this.RaisePropertyChanged("STAFFGW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string STAFFWORK {
            get {
                return this.sTAFFWORKField;
            }
            set {
                this.sTAFFWORKField = value;
                this.RaisePropertyChanged("STAFFWORK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string STAFFMOBILE {
            get {
                return this.sTAFFMOBILEField;
            }
            set {
                this.sTAFFMOBILEField = value;
                this.RaisePropertyChanged("STAFFMOBILE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string STAFFTEL {
            get {
                return this.sTAFFTELField;
            }
            set {
                this.sTAFFTELField = value;
                this.RaisePropertyChanged("STAFFTEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string STAFFEMAIL {
            get {
                return this.sTAFFEMAILField;
            }
            set {
                this.sTAFFEMAILField = value;
                this.RaisePropertyChanged("STAFFEMAIL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public int GJ {
            get {
                return this.gjField;
            }
            set {
                this.gjField = value;
                this.RaisePropertyChanged("GJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int STAFFSF {
            get {
                return this.sTAFFSFField;
            }
            set {
                this.sTAFFSFField = value;
                this.RaisePropertyChanged("STAFFSF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public int STAFFCITY {
            get {
                return this.sTAFFCITYField;
            }
            set {
                this.sTAFFCITYField = value;
                this.RaisePropertyChanged("STAFFCITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public int BBID {
            get {
                return this.bBIDField;
            }
            set {
                this.bBIDField = value;
                this.RaisePropertyChanged("BBID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string STAFFMEMO {
            get {
                return this.sTAFFMEMOField;
            }
            set {
                this.sTAFFMEMOField = value;
                this.RaisePropertyChanged("STAFFMEMO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string JLRQ {
            get {
                return this.jLRQField;
            }
            set {
                this.jLRQField = value;
                this.RaisePropertyChanged("JLRQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public int ISACTIVE {
            get {
                return this.iSACTIVEField;
            }
            set {
                this.iSACTIVEField = value;
                this.RaisePropertyChanged("ISACTIVE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public int BZID {
            get {
                return this.bZIDField;
            }
            set {
                this.bZIDField = value;
                this.RaisePropertyChanged("BZID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public bool SISLOCK {
            get {
                return this.sISLOCKField;
            }
            set {
                this.sISLOCKField = value;
                this.RaisePropertyChanged("SISLOCK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public bool SCANCEL {
            get {
                return this.sCANCELField;
            }
            set {
                this.sCANCELField = value;
                this.RaisePropertyChanged("SCANCEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public bool ISSUPER {
            get {
                return this.iSSUPERField;
            }
            set {
                this.iSSUPERField = value;
                this.RaisePropertyChanged("ISSUPER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string XH {
            get {
                return this.xhField;
            }
            set {
                this.xhField = value;
                this.RaisePropertyChanged("XH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public int E_COUNT {
            get {
                return this.e_COUNTField;
            }
            set {
                this.e_COUNTField = value;
                this.RaisePropertyChanged("E_COUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public int STAFFKHLXID {
            get {
                return this.sTAFFKHLXIDField;
            }
            set {
                this.sTAFFKHLXIDField = value;
                this.RaisePropertyChanged("STAFFKHLXID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public int USERLX {
            get {
                return this.uSERLXField;
            }
            set {
                this.uSERLXField = value;
                this.RaisePropertyChanged("USERLX");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class STAFFDUTY_KH : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int sTAFFIDField;
        
        private string sTAFFNAMEField;
        
        private string dUTYNAMEField;
        
        private string gNAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int STAFFID {
            get {
                return this.sTAFFIDField;
            }
            set {
                this.sTAFFIDField = value;
                this.RaisePropertyChanged("STAFFID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string STAFFNAME {
            get {
                return this.sTAFFNAMEField;
            }
            set {
                this.sTAFFNAMEField = value;
                this.RaisePropertyChanged("STAFFNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DUTYNAME {
            get {
                return this.dUTYNAMEField;
            }
            set {
                this.dUTYNAMEField = value;
                this.RaisePropertyChanged("DUTYNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string GNAME {
            get {
                return this.gNAMEField;
            }
            set {
                this.gNAMEField = value;
                this.RaisePropertyChanged("GNAME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CRM_HG_STAFFList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sTAFFLXDESField;
        
        private string dEPIDDESField;
        
        private string sTAFFZZMMDESField;
        
        private string sTAFFSEXDESField;
        
        private string sTAFFXLDESField;
        
        private string sTAFFHYZKDESField;
        
        private string sTAFFZWJBDESField;
        
        private string sTAFFGWDESField;
        
        private string bZIDDESField;
        
        private string bBIDDESField;
        
        private int sTAFFIDField;
        
        private int dEPIDField;
        
        private string sTAFFNAMEField;
        
        private string sTAFFNOField;
        
        private string sTAFFUSERField;
        
        private string sTAFFPWField;
        
        private int sTAFFLXField;
        
        private string sTAFFRZSJField;
        
        private string sTAFFMPSJField;
        
        private int sTAFFSEXField;
        
        private string sTAFFJGField;
        
        private string sTAFFSFZHField;
        
        private string sTAFFSRField;
        
        private int sTAFFZZMMField;
        
        private int sTAFFXLField;
        
        private string sTAFFBYYXField;
        
        private int sTAFFHYZKField;
        
        private string sTAFFCZDZField;
        
        private int sTAFFZWJBField;
        
        private int sTAFFGWField;
        
        private string sTAFFWORKField;
        
        private string sTAFFMOBILEField;
        
        private string sTAFFTELField;
        
        private string sTAFFEMAILField;
        
        private int gjField;
        
        private int sTAFFSFField;
        
        private int sTAFFCITYField;
        
        private int bBIDField;
        
        private string sTAFFMEMOField;
        
        private string jLRQField;
        
        private int iSACTIVEField;
        
        private int bZIDField;
        
        private bool sISLOCKField;
        
        private bool sCANCELField;
        
        private bool iSSUPERField;
        
        private string xhField;
        
        private int e_COUNTField;
        
        private int sTAFFKHLXIDField;
        
        private int uSERLXDESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string STAFFLXDES {
            get {
                return this.sTAFFLXDESField;
            }
            set {
                this.sTAFFLXDESField = value;
                this.RaisePropertyChanged("STAFFLXDES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DEPIDDES {
            get {
                return this.dEPIDDESField;
            }
            set {
                this.dEPIDDESField = value;
                this.RaisePropertyChanged("DEPIDDES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string STAFFZZMMDES {
            get {
                return this.sTAFFZZMMDESField;
            }
            set {
                this.sTAFFZZMMDESField = value;
                this.RaisePropertyChanged("STAFFZZMMDES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string STAFFSEXDES {
            get {
                return this.sTAFFSEXDESField;
            }
            set {
                this.sTAFFSEXDESField = value;
                this.RaisePropertyChanged("STAFFSEXDES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string STAFFXLDES {
            get {
                return this.sTAFFXLDESField;
            }
            set {
                this.sTAFFXLDESField = value;
                this.RaisePropertyChanged("STAFFXLDES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string STAFFHYZKDES {
            get {
                return this.sTAFFHYZKDESField;
            }
            set {
                this.sTAFFHYZKDESField = value;
                this.RaisePropertyChanged("STAFFHYZKDES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string STAFFZWJBDES {
            get {
                return this.sTAFFZWJBDESField;
            }
            set {
                this.sTAFFZWJBDESField = value;
                this.RaisePropertyChanged("STAFFZWJBDES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string STAFFGWDES {
            get {
                return this.sTAFFGWDESField;
            }
            set {
                this.sTAFFGWDESField = value;
                this.RaisePropertyChanged("STAFFGWDES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string BZIDDES {
            get {
                return this.bZIDDESField;
            }
            set {
                this.bZIDDESField = value;
                this.RaisePropertyChanged("BZIDDES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string BBIDDES {
            get {
                return this.bBIDDESField;
            }
            set {
                this.bBIDDESField = value;
                this.RaisePropertyChanged("BBIDDES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int STAFFID {
            get {
                return this.sTAFFIDField;
            }
            set {
                this.sTAFFIDField = value;
                this.RaisePropertyChanged("STAFFID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int DEPID {
            get {
                return this.dEPIDField;
            }
            set {
                this.dEPIDField = value;
                this.RaisePropertyChanged("DEPID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string STAFFNAME {
            get {
                return this.sTAFFNAMEField;
            }
            set {
                this.sTAFFNAMEField = value;
                this.RaisePropertyChanged("STAFFNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string STAFFNO {
            get {
                return this.sTAFFNOField;
            }
            set {
                this.sTAFFNOField = value;
                this.RaisePropertyChanged("STAFFNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string STAFFUSER {
            get {
                return this.sTAFFUSERField;
            }
            set {
                this.sTAFFUSERField = value;
                this.RaisePropertyChanged("STAFFUSER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string STAFFPW {
            get {
                return this.sTAFFPWField;
            }
            set {
                this.sTAFFPWField = value;
                this.RaisePropertyChanged("STAFFPW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int STAFFLX {
            get {
                return this.sTAFFLXField;
            }
            set {
                this.sTAFFLXField = value;
                this.RaisePropertyChanged("STAFFLX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string STAFFRZSJ {
            get {
                return this.sTAFFRZSJField;
            }
            set {
                this.sTAFFRZSJField = value;
                this.RaisePropertyChanged("STAFFRZSJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string STAFFMPSJ {
            get {
                return this.sTAFFMPSJField;
            }
            set {
                this.sTAFFMPSJField = value;
                this.RaisePropertyChanged("STAFFMPSJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int STAFFSEX {
            get {
                return this.sTAFFSEXField;
            }
            set {
                this.sTAFFSEXField = value;
                this.RaisePropertyChanged("STAFFSEX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string STAFFJG {
            get {
                return this.sTAFFJGField;
            }
            set {
                this.sTAFFJGField = value;
                this.RaisePropertyChanged("STAFFJG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string STAFFSFZH {
            get {
                return this.sTAFFSFZHField;
            }
            set {
                this.sTAFFSFZHField = value;
                this.RaisePropertyChanged("STAFFSFZH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string STAFFSR {
            get {
                return this.sTAFFSRField;
            }
            set {
                this.sTAFFSRField = value;
                this.RaisePropertyChanged("STAFFSR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int STAFFZZMM {
            get {
                return this.sTAFFZZMMField;
            }
            set {
                this.sTAFFZZMMField = value;
                this.RaisePropertyChanged("STAFFZZMM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public int STAFFXL {
            get {
                return this.sTAFFXLField;
            }
            set {
                this.sTAFFXLField = value;
                this.RaisePropertyChanged("STAFFXL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string STAFFBYYX {
            get {
                return this.sTAFFBYYXField;
            }
            set {
                this.sTAFFBYYXField = value;
                this.RaisePropertyChanged("STAFFBYYX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public int STAFFHYZK {
            get {
                return this.sTAFFHYZKField;
            }
            set {
                this.sTAFFHYZKField = value;
                this.RaisePropertyChanged("STAFFHYZK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string STAFFCZDZ {
            get {
                return this.sTAFFCZDZField;
            }
            set {
                this.sTAFFCZDZField = value;
                this.RaisePropertyChanged("STAFFCZDZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public int STAFFZWJB {
            get {
                return this.sTAFFZWJBField;
            }
            set {
                this.sTAFFZWJBField = value;
                this.RaisePropertyChanged("STAFFZWJB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public int STAFFGW {
            get {
                return this.sTAFFGWField;
            }
            set {
                this.sTAFFGWField = value;
                this.RaisePropertyChanged("STAFFGW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string STAFFWORK {
            get {
                return this.sTAFFWORKField;
            }
            set {
                this.sTAFFWORKField = value;
                this.RaisePropertyChanged("STAFFWORK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string STAFFMOBILE {
            get {
                return this.sTAFFMOBILEField;
            }
            set {
                this.sTAFFMOBILEField = value;
                this.RaisePropertyChanged("STAFFMOBILE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string STAFFTEL {
            get {
                return this.sTAFFTELField;
            }
            set {
                this.sTAFFTELField = value;
                this.RaisePropertyChanged("STAFFTEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string STAFFEMAIL {
            get {
                return this.sTAFFEMAILField;
            }
            set {
                this.sTAFFEMAILField = value;
                this.RaisePropertyChanged("STAFFEMAIL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public int GJ {
            get {
                return this.gjField;
            }
            set {
                this.gjField = value;
                this.RaisePropertyChanged("GJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public int STAFFSF {
            get {
                return this.sTAFFSFField;
            }
            set {
                this.sTAFFSFField = value;
                this.RaisePropertyChanged("STAFFSF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public int STAFFCITY {
            get {
                return this.sTAFFCITYField;
            }
            set {
                this.sTAFFCITYField = value;
                this.RaisePropertyChanged("STAFFCITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public int BBID {
            get {
                return this.bBIDField;
            }
            set {
                this.bBIDField = value;
                this.RaisePropertyChanged("BBID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string STAFFMEMO {
            get {
                return this.sTAFFMEMOField;
            }
            set {
                this.sTAFFMEMOField = value;
                this.RaisePropertyChanged("STAFFMEMO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string JLRQ {
            get {
                return this.jLRQField;
            }
            set {
                this.jLRQField = value;
                this.RaisePropertyChanged("JLRQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public int ISACTIVE {
            get {
                return this.iSACTIVEField;
            }
            set {
                this.iSACTIVEField = value;
                this.RaisePropertyChanged("ISACTIVE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public int BZID {
            get {
                return this.bZIDField;
            }
            set {
                this.bZIDField = value;
                this.RaisePropertyChanged("BZID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public bool SISLOCK {
            get {
                return this.sISLOCKField;
            }
            set {
                this.sISLOCKField = value;
                this.RaisePropertyChanged("SISLOCK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public bool SCANCEL {
            get {
                return this.sCANCELField;
            }
            set {
                this.sCANCELField = value;
                this.RaisePropertyChanged("SCANCEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public bool ISSUPER {
            get {
                return this.iSSUPERField;
            }
            set {
                this.iSSUPERField = value;
                this.RaisePropertyChanged("ISSUPER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string XH {
            get {
                return this.xhField;
            }
            set {
                this.xhField = value;
                this.RaisePropertyChanged("XH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public int E_COUNT {
            get {
                return this.e_COUNTField;
            }
            set {
                this.e_COUNTField = value;
                this.RaisePropertyChanged("E_COUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public int STAFFKHLXID {
            get {
                return this.sTAFFKHLXIDField;
            }
            set {
                this.sTAFFKHLXIDField = value;
                this.RaisePropertyChanged("STAFFKHLXID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public int USERLXDES {
            get {
                return this.uSERLXDESField;
            }
            set {
                this.uSERLXDESField = value;
                this.RaisePropertyChanged("USERLXDES");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CRM_Report_STAFFModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int iSACTIVEField;
        
        private int sTAFFLXField;
        
        private string sTAFFNAMEField;
        
        private string sTAFFNOField;
        
        private string sTAFFUSERField;
        
        private string fROMSTAFFMPSJField;
        
        private string tOSTAFFMPSJField;
        
        private int sTAFFSEXField;
        
        private int sTAFFZZMMField;
        
        private int sTAFFXLField;
        
        private int sTAFFZWJBField;
        
        private int sTAFFGWField;
        
        private int dEPIDField;
        
        private string dEPStrField;
        
        private int allSYSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ISACTIVE {
            get {
                return this.iSACTIVEField;
            }
            set {
                this.iSACTIVEField = value;
                this.RaisePropertyChanged("ISACTIVE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int STAFFLX {
            get {
                return this.sTAFFLXField;
            }
            set {
                this.sTAFFLXField = value;
                this.RaisePropertyChanged("STAFFLX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string STAFFNAME {
            get {
                return this.sTAFFNAMEField;
            }
            set {
                this.sTAFFNAMEField = value;
                this.RaisePropertyChanged("STAFFNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string STAFFNO {
            get {
                return this.sTAFFNOField;
            }
            set {
                this.sTAFFNOField = value;
                this.RaisePropertyChanged("STAFFNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string STAFFUSER {
            get {
                return this.sTAFFUSERField;
            }
            set {
                this.sTAFFUSERField = value;
                this.RaisePropertyChanged("STAFFUSER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string FROMSTAFFMPSJ {
            get {
                return this.fROMSTAFFMPSJField;
            }
            set {
                this.fROMSTAFFMPSJField = value;
                this.RaisePropertyChanged("FROMSTAFFMPSJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TOSTAFFMPSJ {
            get {
                return this.tOSTAFFMPSJField;
            }
            set {
                this.tOSTAFFMPSJField = value;
                this.RaisePropertyChanged("TOSTAFFMPSJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int STAFFSEX {
            get {
                return this.sTAFFSEXField;
            }
            set {
                this.sTAFFSEXField = value;
                this.RaisePropertyChanged("STAFFSEX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int STAFFZZMM {
            get {
                return this.sTAFFZZMMField;
            }
            set {
                this.sTAFFZZMMField = value;
                this.RaisePropertyChanged("STAFFZZMM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int STAFFXL {
            get {
                return this.sTAFFXLField;
            }
            set {
                this.sTAFFXLField = value;
                this.RaisePropertyChanged("STAFFXL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int STAFFZWJB {
            get {
                return this.sTAFFZWJBField;
            }
            set {
                this.sTAFFZWJBField = value;
                this.RaisePropertyChanged("STAFFZWJB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int STAFFGW {
            get {
                return this.sTAFFGWField;
            }
            set {
                this.sTAFFGWField = value;
                this.RaisePropertyChanged("STAFFGW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int DEPID {
            get {
                return this.dEPIDField;
            }
            set {
                this.dEPIDField = value;
                this.RaisePropertyChanged("DEPID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string DEPStr {
            get {
                return this.dEPStrField;
            }
            set {
                this.dEPStrField = value;
                this.RaisePropertyChanged("DEPStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int AllSYS {
            get {
                return this.allSYSField;
            }
            set {
                this.allSYSField = value;
                this.RaisePropertyChanged("AllSYS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HG_STAFFSoapChannel : Bussiness.CRM.HG_STAFFService.HG_STAFFSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HG_STAFFSoapClient : System.ServiceModel.ClientBase<Bussiness.CRM.HG_STAFFService.HG_STAFFSoap>, Bussiness.CRM.HG_STAFFService.HG_STAFFSoap {
        
        public HG_STAFFSoapClient() {
        }
        
        public HG_STAFFSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HG_STAFFSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HG_STAFFSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HG_STAFFSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public int Create(Bussiness.CRM.HG_STAFFService.CRM_HG_STAFF model, string ptoken) {
            return base.Channel.Create(model, ptoken);
        }
        
        public int Update(Bussiness.CRM.HG_STAFFService.CRM_HG_STAFF model, string ptoken) {
            return base.Channel.Update(model, ptoken);
        }
        
        public int Delete(int STAFFID, string ptoken) {
            return base.Channel.Delete(STAFFID, ptoken);
        }
        
        public Bussiness.CRM.HG_STAFFService.CRM_HG_STAFFList[] Report(Bussiness.CRM.HG_STAFFService.CRM_Report_STAFFModel model, string TYPE, string ptoken) {
            return base.Channel.Report(model, TYPE, ptoken);
        }
        
        public Bussiness.CRM.HG_STAFFService.CRM_HG_STAFF ReadBySTAFFID(int STAFFID, string ptoken) {
            return base.Channel.ReadBySTAFFID(STAFFID, ptoken);
        }
        
        public Bussiness.CRM.HG_STAFFService.CRM_HG_STAFF ReadBySTAFFNO(string STAFFNO, string ptoken) {
            return base.Channel.ReadBySTAFFNO(STAFFNO, ptoken);
        }
        
        public Bussiness.CRM.HG_STAFFService.CRM_HG_STAFF ReadByROLEID(int ROLEID, string ptoken) {
            return base.Channel.ReadByROLEID(ROLEID, ptoken);
        }
        
        public Bussiness.CRM.HG_STAFFService.CRM_HG_STAFF[] ReadByDUTYID(int DUTYID, string ptoken) {
            return base.Channel.ReadByDUTYID(DUTYID, ptoken);
        }
        
        public Bussiness.CRM.HG_STAFFService.CRM_HG_STAFFList[] ReadByParam(Bussiness.CRM.HG_STAFFService.CRM_HG_STAFF model, string ptoken) {
            return base.Channel.ReadByParam(model, ptoken);
        }
        
        public Bussiness.CRM.HG_STAFFService.CRM_HG_STAFFList[] ReadUser(string ptoken) {
            return base.Channel.ReadUser(ptoken);
        }
        
        public Bussiness.CRM.HG_STAFFService.STAFFDUTY_KH[] ReadSTAFFBYKHIDANDDUTY(int KHID, int DUTYID, string ptoken) {
            return base.Channel.ReadSTAFFBYKHIDANDDUTY(KHID, DUTYID, ptoken);
        }
        
        public Bussiness.CRM.HG_STAFFService.CRM_HG_STAFF[] ReadSTAFF_KHGOURPBYSTAFFID(int STAFFID, string ptoken) {
            return base.Channel.ReadSTAFF_KHGOURPBYSTAFFID(STAFFID, ptoken);
        }
        
        public Bussiness.CRM.HG_STAFFService.CRM_HG_STAFF[] ReadSTAFF_KHGroupByStaffidAndDuty(int STAFFID, int DUTYID, string ptoken) {
            return base.Channel.ReadSTAFF_KHGroupByStaffidAndDuty(STAFFID, DUTYID, ptoken);
        }
        
        public Bussiness.CRM.HG_STAFFService.CRM_HG_STAFF[] ReadStaff_BYDEPID(int STAFFID, string ptoken) {
            return base.Channel.ReadStaff_BYDEPID(STAFFID, ptoken);
        }
        
        public Bussiness.CRM.HG_STAFFService.CRM_HG_STAFFList[] ReadUser_STAFF(Bussiness.CRM.HG_STAFFService.CRM_Report_STAFFModel model, string ptoken) {
            return base.Channel.ReadUser_STAFF(model, ptoken);
        }
    }
}
