//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace STSY.KQInfoService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="KQinfoSoap", Namespace="http://Sonluk.com/API/KQ/")]
    public partial class KQinfo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getKQINFOOperationCompleted;
        
        private System.Threading.SendOrPostCallback StaffCardIDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public KQinfo() {
            this.Url = global::STSY.Properties.Settings.Default.STSY_KQInfoService_KQinfo;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getKQINFOCompletedEventHandler getKQINFOCompleted;
        
        /// <remarks/>
        public event StaffCardIDCompletedEventHandler StaffCardIDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Sonluk.com/API/KQ/getKQINFO", RequestNamespace="http://Sonluk.com/API/KQ/", ResponseNamespace="http://Sonluk.com/API/KQ/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public KQINFO getKQINFO(string date) {
            object[] results = this.Invoke("getKQINFO", new object[] {
                        date});
            return ((KQINFO)(results[0]));
        }
        
        /// <remarks/>
        public void getKQINFOAsync(string date) {
            this.getKQINFOAsync(date, null);
        }
        
        /// <remarks/>
        public void getKQINFOAsync(string date, object userState) {
            if ((this.getKQINFOOperationCompleted == null)) {
                this.getKQINFOOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetKQINFOOperationCompleted);
            }
            this.InvokeAsync("getKQINFO", new object[] {
                        date}, this.getKQINFOOperationCompleted, userState);
        }
        
        private void OngetKQINFOOperationCompleted(object arg) {
            if ((this.getKQINFOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getKQINFOCompleted(this, new getKQINFOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Sonluk.com/API/KQ/StaffCardID", RequestNamespace="http://Sonluk.com/API/KQ/", ResponseNamespace="http://Sonluk.com/API/KQ/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string StaffCardID(string cardno) {
            object[] results = this.Invoke("StaffCardID", new object[] {
                        cardno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void StaffCardIDAsync(string cardno) {
            this.StaffCardIDAsync(cardno, null);
        }
        
        /// <remarks/>
        public void StaffCardIDAsync(string cardno, object userState) {
            if ((this.StaffCardIDOperationCompleted == null)) {
                this.StaffCardIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStaffCardIDOperationCompleted);
            }
            this.InvokeAsync("StaffCardID", new object[] {
                        cardno}, this.StaffCardIDOperationCompleted, userState);
        }
        
        private void OnStaffCardIDOperationCompleted(object arg) {
            if ((this.StaffCardIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StaffCardIDCompleted(this, new StaffCardIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Sonluk.com/API/KQ/")]
    public partial class KQINFO {
        
        private string count1Field;
        
        private string count2Field;
        
        /// <remarks/>
        public string Count1 {
            get {
                return this.count1Field;
            }
            set {
                this.count1Field = value;
            }
        }
        
        /// <remarks/>
        public string Count2 {
            get {
                return this.count2Field;
            }
            set {
                this.count2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    public delegate void getKQINFOCompletedEventHandler(object sender, getKQINFOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getKQINFOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getKQINFOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KQINFO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KQINFO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    public delegate void StaffCardIDCompletedEventHandler(object sender, StaffCardIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StaffCardIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StaffCardIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591